In [14]:
import numpy as np
import pandas as pd

In [4]:
dataset = pd.read_csv('exoPlanets.csv')

In [20]:
X = dataset.iloc[: , 1:].values
Y = dataset.iloc[: , 0].values
print(X)

[[ 93.85  83.81  20.1  ...  61.42   5.08 -39.54]
 [-38.88 -33.83 -58.54 ...   6.46  16.    19.93]
 [532.64 535.92 513.73 ... -28.91 -70.02 -96.67]
 ...
 [273.39 278.   261.73 ...  88.42  79.07  79.43]
 [  3.82   2.09  -3.29 ... -14.55  -6.41  -2.55]
 [323.28 306.36 293.16 ... -16.72 -14.09  27.82]]


In [6]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan , strategy='mean')
imputer.fit(X[: , 1:])
X[: , 1:]= imputer.transform(X[: , 1:])
print(X)

[[  2.    93.85  83.81 ...  39.32  61.42   5.08]
 [  2.   -38.88 -33.83 ... -11.7    6.46  16.  ]
 [  2.   532.64 535.92 ... -11.8  -28.91 -70.02]
 ...
 [  1.   273.39 278.   ...  65.73  88.42  79.07]
 [  1.     3.82   2.09 ...  -4.65 -14.55  -6.41]
 [  1.   323.28 306.36 ... -41.31 -16.72 -14.09]]


In [24]:
nan_values = dataset.isna()  # Returns a DataFrame with True for NaN values
nan_values_count = dataset.isna().sum()  # Returns the count of NaN values in each column

# Display the DataFrame with True for NaN values
print("DataFrame with True for NaN values:")
print(nan_values)

DataFrame with True for NaN values:
      LABEL  FLUX.1  FLUX.2  FLUX.3  FLUX.4  FLUX.5  FLUX.6  FLUX.7  FLUX.8  \
0     False   False   False   False   False   False   False   False   False   
1     False   False   False   False   False   False   False   False   False   
2     False   False   False   False   False   False   False   False   False   
3     False   False   False   False   False   False   False   False   False   
4     False   False   False   False   False   False   False   False   False   
...     ...     ...     ...     ...     ...     ...     ...     ...     ...   
5082  False   False   False   False   False   False   False   False   False   
5083  False   False   False   False   False   False   False   False   False   
5084  False   False   False   False   False   False   False   False   False   
5085  False   False   False   False   False   False   False   False   False   
5086  False   False   False   False   False   False   False   False   False   

      FLUX.9  .

In [25]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y, test_size=0.2,random_state=0)
print(X_train)
print(X_test)
print(Y_train)
print(Y_test)

[[-2.4000e-01  2.3200e+00  6.8000e-01 ...  1.8760e+01  1.0610e+01
   4.8400e+00]
 [-7.1000e-01 -5.7400e+00  6.9100e+00 ...  2.2170e+01  2.8280e+01
   3.3190e+01]
 [ 3.5743e+02  3.1859e+02  3.1365e+02 ...  8.7860e+01  7.4920e+01
   4.2620e+01]
 ...
 [ 2.7360e+01  3.8730e+01  3.5090e+01 ...  3.5492e+02  3.0440e+02
   2.4711e+02]
 [ 1.1210e+01  1.7100e+00  1.3350e+01 ... -1.9000e-01 -1.3580e+01
  -1.0570e+01]
 [ 1.0230e+01  3.0000e-01 -2.5800e+00 ... -4.8480e+01 -3.4420e+01
  -4.3840e+01]]
[[-422.24 -425.42 -413.99 ... -497.91 -468.84 -407.23]
 [   5.8     4.49   -0.84 ...    3.3    -2.42    2.42]
 [  21.65   20.3    10.92 ...   10.91   15.32    7.79]
 ...
 [  23.78   17.54   10.82 ...   23.6    -2.52    5.4 ]
 [ -13.16   -9.75    8.05 ...  -10.66  -34.89   -1.86]
 [ -46.88 -104.24  -34.9  ...   16.29  -21.13   13.92]]
[1 1 1 ... 1 1 1]
[1 1 1 ... 1 1 1]


In [26]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[: , 3:])
X_test[:, 3:] = sc.transform(X_test[: , 3:])

In [ ]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression(random_state = 0)
classifier = LogisticRegression(max_iter=1000)
classifier.fit(X_train, Y_train)

In [ ]:
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

# Load a dataset (e.g., the Iris dataset for demonstration)
iris = pd.read_csv('exoPlanets.csv')
X = iris.iloc[: , 1:].values
y = iris.iloc[: , 0].values

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create an SVM classifier (SVC for classification)
model = SVC(kernel='linear', C=1.0)  # You can choose different kernels (linear, rbf, etc.) and C values

# Train the model on the training data
model.fit(X_train, y_train)

# Make predictions on the test data
y_pred = model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

# Print a classification report for more detailed evaluation metrics
class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)


In [58]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns
import sklearn
df=pd.read_csv('exoPlanets.csv')
df.describe()
X = df.iloc[: , 1:].values
Y = df.iloc[: , 0].values
print(X)
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan , strategy='mean')
imputer.fit(X[: , 1:])
X[: , 1:]= imputer.transform(X[: , 1:])
from sklearn.ensemble import RandomForestClassifier

# Initialize the classifier
clf = RandomForestClassifier()

# Fit the model to your data
clf.fit(X, Y)  # X is your feature matrix, y is your target labels

# Get feature importances
feature_importances = clf.feature_importances_
# Assuming you have a DataFrame 'df' with feature names
feature_importance_df = pd.DataFrame({'Feature': df.columns[1:], 'Importance': feature_importances})

# Sort the features by importance in descending order
feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=True)

# Print or visualize the top N important features (you can change N as needed)
N = 10  # Adjust this based on how many top features you want to see
top_features = feature_importance_df.head(N)
print(top_features)
# Find features with 0 importance
zero_importance_features = feature_importance_df[feature_importance_df['Importance'] == 0]['Feature']

# Remove features with 0 importance from your DataFrame 'df'
df_filtered = df.drop(columns=zero_importance_features)

# Print the updated DataFrame
print(df_filtered)
# Assuming your DataFrame is named 'df'
num_columns = df_filtered.shape[1]
print("Number of columns in the dataset:", num_columns)
X_filtered = df_filtered.iloc[: , 1:].values
print(X)
from sklearn.model_selection import train_test_split
X_filtered_train, X_filtered_test, Y_train, Y_test = train_test_split(X_filtered, Y, test_size=0.3, random_state=0)
# Step 4: Create a KNN classifier and set hyperparameters to tune
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
knn = KNeighborsClassifier()
param_grid = {
    'n_neighbors': [3, 5, 7, 9],  # Values of k to be tuned
    'weights': ['uniform', 'distance'],  # Weighting strategy
    'p': [1, 2]  # 1 for Manhattan distance, 2 for Euclidean distance
}
# Step 5: Perform GridSearchCV for hyperparameter tuning
grid_search = GridSearchCV(estimator=knn, param_grid=param_grid, scoring='accuracy', cv=5)
grid_search.fit(X_filtered_train, Y_train)
# Get the best hyperparameters from the grid search
best_params = grid_search.best_params_
print(f'Best Hyperparameters: {best_params}')
# Step 6: Create a KNN classifier with the best hyperparameters
best_knn = KNeighborsClassifier(**best_params)
# Step 7: Train the classifier on the training data
best_knn.fit(X_filtered_train, Y_train)
# Step 8: Make predictions on the testing data
Y_pred = best_knn.predict(X_filtered_test)
# Step 9: Evaluate the classifier's performance
accuracy = accuracy_score(Y_test, Y_pred)
print(f'Accuracy: {accuracy:.2f}')


[[ 93.85  83.81  20.1  ...  61.42   5.08 -39.54]
 [-38.88 -33.83 -58.54 ...   6.46  16.    19.93]
 [532.64 535.92 513.73 ... -28.91 -70.02 -96.67]
 ...
 [273.39 278.   261.73 ...  88.42  79.07  79.43]
 [  3.82   2.09  -3.29 ... -14.55  -6.41  -2.55]
 [323.28 306.36 293.16 ... -16.72 -14.09  27.82]]
        Feature  Importance
3196  FLUX.3197         0.0
819    FLUX.820         0.0
1960  FLUX.1961         0.0
1963  FLUX.1964         0.0
816    FLUX.817         0.0
815    FLUX.816         0.0
1964  FLUX.1965         0.0
820    FLUX.821         0.0
812    FLUX.813         0.0
810    FLUX.811         0.0
      LABEL   FLUX.1   FLUX.5   FLUX.6   FLUX.8  FLUX.9  FLUX.10  FLUX.13  \
0         2    93.85   -39.56  -124.71   -96.27  -79.89  -160.17  -173.71   
1         2   -38.88   -79.31   -72.81   -85.33  -83.97   -73.38   -73.15   
2         2   532.64   456.45   466.00   486.39  436.56   484.39   492.23   
3         2   326.52   317.74   312.70   311.31  312.42   323.33   313.11   
4      